name: Pull Request Checks

on:
    pull_request:
        branches: [main, develop, 'release/**']

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '>=18'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Check TypeScript
              run: npm run typecheck

            - name: Run linter
              run: npm run lint

            - name: 'Test Coverage'
              run: npm run test:coverage

            - name: 'Report Coverage'
              if: always()
              uses: davelosert/vitest-coverage-report-action@v2
